### ISSUE TITLE
Performance on real word dataset.

### ISSUE THREAD

**Issue by XuyangBai** [WangYueFt/prnet#3]
Hi @WangYueFt   Thanks for your sharing!  In the paper, you claimed PRNET is able to handle partial-to-partial registration, but I think in the experiment, you use the rotation sample from [0, 45] and translation in [-0.5, 0.5], which might still result in two point clouds with a quite large overlap. So I wonder have you ever test the model on real world dataset like 3DMatch where the overlap between two point clouds are small?

**Comment by WangYueFt** [comment]
> Hi @WangYueFt Thanks for your sharing! In the paper, you claimed PRNET is able to handle partial-to-partial registration, but I think in the experiment, you use the rotation sample from [0, 45] and translation in [-0.5, 0.5], which might still result in two point clouds with a quite large overlap. So I wonder have you ever test the model on real world dataset like 3DMatch where the overlap between two point clouds are small?

Hi Xuyang,

I didn't test it on the 3DMatch dataset and we're still working on that.
