### ISSUE TITLE
cuDNN issues

### ISSUE THREAD

**Issue by SebastianGrans** [WangYueFt/prnet#5]
This is not a problem with the repo it self, but rather the underlying packages. I thought I could add it here if anyone else was experiencing the same issues. 

When I run it, I get the error ` CUDNN_STATUS_NOT_SUPPORTED`. I managed to work around this by adding the following to `main.py`: `torch.backends.cudnn.enabled = False`. Essentially disabling cuDNN. 

```
Traceback (most recent call last):
  File "main.py", line 177, in <module>
    main()
  File "main.py", line 171, in main
    train(args, net, train_loader, test_loader)
  File "main.py", line 49, in train
    info_train = net._train_one_epoch(epoch=epoch, train_loader=train_loader, opt=opt)
  File "/home/grans/Documents/prnet/model.py", line 704, in _train_one_epoch
    opt)
  File "/home/grans/Documents/prnet/model.py", line 643, in _train_one_batch
    total_loss.backward()
  File "/home/grans/.local/lib/python3.6/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/grans/.local/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.
```

**Comment by WangYueFt** [comment]
> This is not a problem with the repo it self, but rather the underlying packages. I thought I could add it here if anyone else was experiencing the same issues.
> 
> When I run it, I get the error ` CUDNN_STATUS_NOT_SUPPORTED`. I managed to work around this by adding the following to `main.py`: `torch.backends.cudnn.enabled = False`. Essentially disabling cuDNN.
> 
> ```
> Traceback (most recent call last):
>   File "main.py", line 177, in <module>
>     main()
>   File "main.py", line 171, in main
>     train(args, net, train_loader, test_loader)
>   File "main.py", line 49, in train
>     info_train = net._train_one_epoch(epoch=epoch, train_loader=train_loader, opt=opt)
>   File "/home/grans/Documents/prnet/model.py", line 704, in _train_one_epoch
>     opt)
>   File "/home/grans/Documents/prnet/model.py", line 643, in _train_one_batch
>     total_loss.backward()
>   File "/home/grans/.local/lib/python3.6/site-packages/torch/tensor.py", line 195, in backward
>     torch.autograd.backward(self, gradient, retain_graph, create_graph)
>   File "/home/grans/.local/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
>     allow_unreachable=True)  # allow_unreachable flag
> RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.
> ```

Good catch! Thanks for posting this. 

Best,
Yue
